import type { Metadata } from "next";
import localFont from "next/font/local";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "../components/theme/theme-provider";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Sidebar from "@/components/sidebar/Sidebar";
import { Toaster } from "react-hot-toast";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Social Network",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        {/* This is the root layout for the app and the main container. It wraps all pages and components.*/}
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased text-gray-800
           bg-background font-sans dark:bg-gradient-to-r from-[#1a263d] to-[#304c6d] dark:text-gray-200`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="min-h-screen">
              <Navbar />
              <main className="py-8 ">
                {/* Container to center the content */}
                <div className="max-w-7xl mx-auto px-4">
                  <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
                    <div className="hidden lg:block lg:col-span-3">
                      <Sidebar />
                    </div>
                    <div className="lg:col-span-9">
                      <Toaster position="top-right" />

                      {children}
                    </div>
                  </div>
                </div>
              </main>
            </div>
            {/*This `children` renders the page.tsx(general route), This is where the page content will be rendered */}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
